service: hello-sls
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.hello
    events:
      - http:
          path: hello
          method: get
